### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by m-mohr** [covjson/specification#87]
Hello,

I just discovered this and wondered what the status is? The version is 0.2-draft and the last commit was two years ago. Is this repository abandoned and the spec never released a stable version or is there still work going on and we can expect a stable version at some point? 

Thanks.

**Comment by jonblower** [comment]
Hi, thanks for your interest! For practical purposes, I consider the current version "stable", in that we have not seen a need to make a change for a while, and the spec is being actively used in a few projects. However, as you have noted, there has not been a formal release yet, mainly because of a lack of resources and a lack of a formal process. (We are working on this, slowly...)

So this effort is certainly not abandoned, and I would encourage you to check it out and use this, as others are. We and other users would be happy to help you I'm sure. You might like to look at the following related resources too (which I really ought to link from the website):

- [Overview of the CoverageJSON format](https://www.w3.org/TR/covjson-overview/), published as a joint OGC/W3C Note

- "Building rich and interactive websites with CoverageJSON" [video](https://ecmwf.adobeconnect.com/p6224btxzng/) and [slides](https://www.ecmwf.int/sites/default/files/elibrary/2017/17149-building-rich-and-interactive-web-applications-coveragejson.pdf).
- As well as the CovJSON [website](https://covjson.org) of course.

**Comment by lewismc** [comment]
OK follow-up here folks, James Gallagher kindly updated the Hyrax test instance at test.opendap.org to 1.15.0 so you can now see the CovJSON integration for yourself.
An example http://test.opendap.org/opendap/AIRS/contents.html. Here you can see the usual access mechanisms under the DAP RESPONSE LINKS area with the addition of the new covjson link.
Additionally, if you actually inspect the granule itself, http://test.opendap.org/opendap/AIRS/QC_AIRS-1.2011.02.13.090.L2.RetStd.v5.2.2.0.G11045052855.hdf.html you can see the addition of the new ‘Get as CoverageJSON’ button.
Finally, you can just apply the correct file suffix and it will directly retrieve the granule in the CovJSON serialization http://test.opendap.org/opendap/AIRS/QC_AIRS-1.2011.02.13.090.L2.RetStd.v5.2.2.0.G11045052855.hdf.covjson
